server:
  port: 8090
spring:
  profiles:
    active: dev
  datasource: 
#    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jaya_example
    url: jdbc:mysql://localhost:3306/jaya_test
    username: root
#    password: root
    password: 12345678
  mvc:
    static-path-pattern: /static/**
logging:
  path: log/
  file: demo.log
  level: 
    root: dubug
    com:
      jaya:
        demo: debug
test: 
  abc: cba
---
tttt:
  cba: abc