server:
  port: 8090
  context-path: ""
spring:
  datasource: 
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jaya_example
    url: jdbc:mysql://localhost:3306/jaya_test
    username: root
#    password: root
    password: 12345678
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  path: log/
  file: demo.log
  level: 
    root: dubug
    com.jaya.demo: debug
