server:
  port: 8090
spring:
  datasource:
    type: 
    dbcp:
      url: jdbc:mysql://localhost:3306/jaya_test
      username: root
      password: 12345678
  thymeleaf:
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
    prefix: classpath:/templates/
logging:
  path: log/
  file: demo.log
  level:
    root: error
    com.jaya.demo: debug
